
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    # dbcp2:
      # driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    password:
# logging.level.com.my.test.redismysql.dao: debug
